personal:
  name: "林韋廷"
  name_en: "Wei Ting Lin"
  title: "AI Engineer | Bioinformatics Specialist"
  email: "leetin@myyahoo.com"
  linkedin: "https://www.linkedin.com/in/韋廷-林-3b9ab11aa"
  description: "專精自然語言處理、深度學習與生醫AI設計，擁有跨領域的研究與實務經驗，熱衷於打造高效能的AI模型解決實際問題。"
  avatar: "avatar.jpg"
  about: |
    我是韋廷，目前擔任AI工程師，專注於結合AI與生物資訊解決醫療與藥物開發中的複雜問題。從自然語言處理到結構生物資訊，我不僅具備強大的統計分析基礎，還能設計、開發與部署深度學習模型。

    在研究與實務經驗中，我曾參與蛋白質修飾位點預測、結構模擬、以及病理聲音多模態分類等AI專案。對於跨領域合作與轉化AI技術到臨床與藥物研發應用充滿熱情，持續透過專案累積專業能力與產業經驗。
  institution: "國立陽明交通大學生物資訊及系統生物研究所"
experiences:

  - title: "專任研究助理"
    company: "國家衛生研究院 生技及藥物研究所"
    period: "2021.8 - 2025.4"
    skills: ["Python", "Deep Learning", "AI Drug Development", "Server Management"]
    tasks:
      - "協助建立AI藥物研發工作流程，開發化合物性質預測及分子特徵選擇模型。"
      - "設計神經網路架構，提升藥物特性預測、化合物篩選與結構優化的準確度。"
      - "監控並維護高效能運算伺服器狀態，確保模型訓練與推論的穩定執行。"
      - "支援跨部門AI技術需求，針對同事問題提供技術諮詢與解決方案。"
  - title: "專任研究助理"
    company: "台北醫學大學 大數據科技及管理研究所"
    period: "2021.3 - 2021.7"
    skills: ["NLP", "Text Mining", "Deep Learning (CNN/RNN)"]
    tasks:
      - "應用 NLP 技術進行臨床醫療紀錄文本處理，包括前處理、分詞、特徵萃取等。"
      - "建構CNN、RNN等深度學習模型，執行文本分類、情感分析與命名實體識別。"
      - "整合資料庫與前端視覺化工具，提升資料應用效益與使用者體驗。"

projects:
  - title: "AI輔助CRISPR/Cas9效率預測"
    image: "CRISPR.jpg"
    preview_url: ""
    skills: ["Multi-task Learning", "Transformer"]
    description: "利用基於Transformer架構的多任務學習模型，同步預測CRISPR靶點效率與特定指標，協助基因編輯設計流程。"
    link: ""

  - title: "AICUP 醫病決策競賽"
    image: "2021_aicup.jpg"
    preview_url: ""
    skills: ["LSTM", "BERT"]
    description: "結合LSTM和BERT進行病患決策預測模型開發，分析病歷文本以協助臨床決策。"
    link: ""

  - title: "企業數據競賽亞軍專案"
    image: "data_sta.jpg"
    preview_url: ""
    skills: ["Data Science"]
    description: "2021企業數據競賽 玩美移動組 亞軍，運用資料探索、特徵工程及模型開發提升預測效能。"
    link: ""

  - title: "多模態病理嗓音分類 (AICUP 2023)"
    image: "multi-modal.jpg"
    preview_url: "https://www.aicup.tw/post/%E3%80%90%E5%BE%97%E7%8D%8E%E5%90%8D%E5%96%AE%E3%80%91ai-cup-2023-%E6%98%A5%E5%AD%A3%E8%B3%BD%E3%80%8C%E5%A4%9A%E6%A8%A1%E6%85%8B%E7%97%85%E7%90%86%E5%97%93%E9%9F%B3%E5%88%86%E9%A1%9E%E3%80%8D%E7%AB%B6%E8%B3%BD"
    skills: ["Multi-modal Learning", "Audio Processing"]
    description: "整合聲音與元數據的多模態模型，有效區分病理與正常嗓音，協助病症診斷。"
    link: "https://github.com/garh305111/AI-CUP-2023-SPRING--"

skills:
  technical:
    - "Python"
    - "Deep Learning (CNN, RNN, Transformer)"
    - "Large Language Models"
    - "Golang"
    - "MongoDB"
    - "Docker & Server Management"
    - "Git & CI/CD"

  certificates:
    - "AICUP 醫病決策競賽 前標"
    - "2021企業數據競賽 亞軍"
    - "機器學習工程師認證"
    - "統計分析能力證照"